use_list = ['', '', '', '', '', '', '', '', '', '', '', '']
data_name_list = ['R_BusinessCycle_First_row_extre_0.3',
                  'R_CurrentAssets_TotAssets_First_row_extre_0.3',
                  'R_CurrentAssetsTurnover_First_row_extre_0.3',
                  'R_DebtAssets_First_row_extre_0.3',
                  'R_DebtEqt_First_row_extre_0.3',
                  'R_OPCF_IntDebt_QTTM_row_extre_0.3',
                  'R_IntDebt_Mcap_First_row_extre_0.3',
                  'R_OPEX_sales_TTM_Y3YGR_row_extre_0.3',
                  'R_EBITDA_sales_TTM_First_row_extre_0.3',
                  'R_EBITDA_sales_TTM_QTTM_row_extre_0.3',
                  'R_ROA_TTM_Y3YGR_row_extre_0.3',
                  'R_OPCF_TotDebt_QYOY_row_extre_0.3',
                  'R_OPCF_TotDebt_First_row_extre_0.3',
                  'R_OPCF_NetInc_s_First_row_extre_0.3',
                  'R_OPCF_sales_First_row_extre_0.3',
                  'R_EBITDA_QTTM_and_R_SUMASSET_First_0.3',
                  'R_EBIT2_Y3YGR_and_MCAP_0.3',
                  'R_EBITDA_QYOY_and_MCAP_0.3',
                  'R_IntDebt_Y3YGR_and_R_SUMASSET_First_0.3',
                  'CCI_p120d_limit_12',
                  'MACD_20_100',
                  'log_price_0.2',
                  'bias_turn_p20d',
                  'vol_p20d',
                  'vol_p20d',
                  'evol_p20d'
                  ]